app/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import home, service, portfolio, about, pricing, contact, blog


urlpatterns = [
    path('', home.index, name="index"),
    path('services', service.index, name="service"),

    path('portfolio', portfolio.index, name="portfolio"),
    path('portfolio/<str:slug>', portfolio.show, name="portfolio.show"),

    path('about', about.index, name="about"),
    path('pricing', pricing.index, name="pricing"),
    path('contact', contact.index, name="contact"),

    #blog
    path('blog', blog.index, name="blog.index"),
    path('blog/<str:slug>', blog.show, name="blog.show"),
    path('blog/category/<str:slug>', blog.category, name="blog.category"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/models.py
from django.db import models
from colorfield.fields import ColorField
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User

# Create your models here.

class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='user/')
    short_description = models.TextField(max_length=255)
    details = RichTextField()

    def __str__(self):
        return self.user.first_name



class Category(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)

    def __str__(self):
        return self.title
    

class Type(models.Model):
    title = models.CharField(max_length=255)

    def __str__(self):
        return self.title


class Client(models.Model):
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=15)
    email = models.CharField(max_length=255, unique=True)
    address = models.CharField(max_length=255)
    company = models.CharField(max_length=150, null=True, blank=True)
    position = models.CharField(max_length=255)
    image = models.ImageField(upload_to='client/')
    details = RichTextField(null=True, blank=True)

    def __str__(self):
        return self.name
    


class Language(models.Model):
    name = models.CharField(max_length=100)
    logo = models.ImageField(upload_to='language/', null=True, blank=True)

    def __str__(self):
        return self.name
    


class Project(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    link = models.CharField(max_length=255, null=True, blank=True)
    type = models.ForeignKey(Type, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='project/', help_text="Image size must be 768*576 px")
    cover = models.ImageField(upload_to='project/', help_text="Image size must be 1900*835 px")
    client = models.ForeignKey(Client, on_delete=models.Case)
    date = models.DateField()
    details = RichTextField()
    language = models.ManyToManyField(Language)

    def __str__(self):
        return self.title
    

class Project_Feature(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    feature = models.CharField(max_length=255)


class Project_image(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    title = models.CharField(max_length=255, null=True, blank=True)
    image = models.ImageField(upload_to='project/', null=True, blank=True)




class Service(models.Model):
    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to='service/')
    details = models.TextField( max_length=255)

    def __str__(self):
        return self.title
    


class Skill(models.Model):
    title = models.CharField(max_length=50)
    icon = models.ImageField(upload_to='skill/')
    percentage = models.IntegerField()

    def __str__(self):
        return self.title
    


class Education(models.Model):
    degree = models.CharField(max_length=100)
    college = models.CharField(max_length=150)
    date = models.CharField(max_length=50)
    details = models.TextField(max_length=200)

    def __str__(self):
        return self.degree
    

FREELANCE_STATUS = (
    ('Available','Available'),
    ('Unavailable','Unavailable'),

)

class Info(models.Model):
    name = models.CharField(max_length=255)
    birth_day = models.DateField()
    address = models.CharField(max_length=255)
    email = models.CharField(max_length=100)
    phone = models.CharField(max_length=15)
    skype = models.CharField(max_length=100)
    freelance = models.CharField(max_length=15, choices=FREELANCE_STATUS, default="Available")

    def __str__(self):
        return self.name
    


class Brand(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='brands/')

    def __str__(self):
        return self.name



class Feedback(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    feedback = models.TextField(max_length=255)

    def __str__(self):
        return self.client.name
    


class BlogCategory(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)

    def __str__(self):
        return self.title
    


class Tag(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)

    def __str__(self):
        return self.title
    

class Blog(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='project/', help_text="Image size must be 800*600 px")
    cover = models.ImageField(upload_to='project/', help_text="Image size must be 1500*840 px")
    blog = RichTextField()
    tags = models.ManyToManyField(Tag)
    meta_description = models.CharField(max_length=255, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)


    def __str__(self):
        return self.title
    

class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    comment = models.TextField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)


    def __str__(self):
        return self.blog.title
    
    class Meta:
        ordering = ('created_at', )
    

class Reply(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, null=True, blank=True)
    reply = models.TextField(max_length=500, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)




#pricing
class Pricing(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    price = models.CharField(max_length=100)
    icon = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class Pricing_Options(models.Model):
    pricing = models.ForeignKey(Pricing, on_delete=models.CASCADE)
    option = models.CharField(max_length=255)




STATUS_CHOICES = (
    ('pending','Pending'),
    ('received', 'Received'),
    ('running','Running'),
    ('completed','Completed'),
    ('canceled','Canceled'),
)

class Order(models.Model):
    pricing = models.ForeignKey(Pricing, on_delete=models.CASCADE)
    subject = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    phone = models.CharField(max_length=15)
    details = models.TextField()
    budget = models.CharField(max_length=100)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="pending")

app/views/pricing.py
from django.shortcuts import render

from ..models import Pricing

def index(request):
    pricings = Pricing.objects.all()

    context = {
        'pricings': pricings
    }

    return render(request, 'pricing/index.html', context)

app/templates/pricing/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- Start Pricing 
    ============================================= -->
<div id="pricing" class="pricing-area default-padding">
    <div class="container">
        <div class="pricing-box">
            <div class="row">
                <div class="col-lg-5">
                    <div class="heading-left">
                        <div class="left-info">
                            <h5 class="sub-title">Pricing</h5>
                            <h2 class="title">The best pricing plans <br> to get your best</h2>
                            <div class="heading-shape">
                                <img src="{% static 'assets/img/shape/10.png' %}" alt="Shape">
                            </div>
                        </div>
                    </div>
                    <div class="save-ammount mt-100 mt-md-50">
                        <h4>Grow up your <strong>Business</strong> with a website you want</h4>
                        <img src="{% static 'assets/img/shape/2.webp'%}" alt="Thumb">
                    </div>
                </div>
                <div class="col-lg-6 offset-lg-1">
                    {% for pricing in pricings %}
                    <div class="pricing-style-one">
                        <div class="conntent" style="flex-basis: 65%;">
                            <h4>{{ pricing.title }}</h4>
                            <ul>
                                {% for option in pricing.pricing_options_set.all %}
                                <li>{{ option.option }}</li>
                                {% endfor %}
                                
                            </ul>
                            <a class="btn mt-25 btn-sm circle {% if forloop.first %}btn-theme {% else %} btn-dark {% endif %}" href="#contact">Order Now</a>
                        </div>
                        <div class="price" style="flex-basis: 35%;">
                            <h2><sup>৳</sup> {{ pricing.price }}</h2>
                            {{ pricing.icon | safe }}
                        </div>
                    </div>
                    {% endfor %}
                
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Pricing Area -->
{% endblock %}