app/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import home, service, portfolio, about, pricing, contact, blog


urlpatterns = [
    path('', home.index, name="index"),
    path('services', service.index, name="service"),

    path('portfolio', portfolio.index, name="portfolio"),
    path('portfolio/<str:slug>', portfolio.show, name="portfolio.show"),

    path('about', about.index, name="about"),
    path('pricing', pricing.index, name="pricing"),
    path('contact', contact.index, name="contact"),

    #blog
    path('blog', blog.index, name="blog.index"),
    path('blog/<str:slug>', blog.show, name="blog.show"),
    path('blog/category/<str:slug>', blog.category, name="blog.category"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/models.py
from django.db import models
from colorfield.fields import ColorField
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User

# Create your models here.

class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='user/')
    short_description = models.TextField(max_length=255)
    details = RichTextField()

    def __str__(self):
        return self.user.first_name



class Category(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)

    def __str__(self):
        return self.title
    

class Type(models.Model):
    title = models.CharField(max_length=255)

    def __str__(self):
        return self.title


class Client(models.Model):
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=15)
    email = models.CharField(max_length=255, unique=True)
    address = models.CharField(max_length=255)
    company = models.CharField(max_length=150, null=True, blank=True)
    position = models.CharField(max_length=255)
    image = models.ImageField(upload_to='client/')
    details = RichTextField(null=True, blank=True)

    def __str__(self):
        return self.name
    


class Language(models.Model):
    name = models.CharField(max_length=100)
    logo = models.ImageField(upload_to='language/', null=True, blank=True)

    def __str__(self):
        return self.name
    


class Project(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    link = models.CharField(max_length=255, null=True, blank=True)
    type = models.ForeignKey(Type, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='project/', help_text="Image size must be 768*576 px")
    cover = models.ImageField(upload_to='project/', help_text="Image size must be 1900*835 px")
    client = models.ForeignKey(Client, on_delete=models.Case)
    date = models.DateField()
    details = RichTextField()
    language = models.ManyToManyField(Language)

    def __str__(self):
        return self.title
    

class Project_Feature(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    feature = models.CharField(max_length=255)


class Project_image(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    title = models.CharField(max_length=255, null=True, blank=True)
    image = models.ImageField(upload_to='project/', null=True, blank=True)




class Service(models.Model):
    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to='service/')
    details = models.TextField( max_length=255)

    def __str__(self):
        return self.title
    


class Skill(models.Model):
    title = models.CharField(max_length=50)
    icon = models.ImageField(upload_to='skill/')
    percentage = models.IntegerField()

    def __str__(self):
        return self.title
    


class Education(models.Model):
    degree = models.CharField(max_length=100)
    college = models.CharField(max_length=150)
    date = models.CharField(max_length=50)
    details = models.TextField(max_length=200)

    def __str__(self):
        return self.degree
    

FREELANCE_STATUS = (
    ('Available','Available'),
    ('Unavailable','Unavailable'),

)

class Info(models.Model):
    name = models.CharField(max_length=255)
    birth_day = models.DateField()
    address = models.CharField(max_length=255)
    email = models.CharField(max_length=100)
    phone = models.CharField(max_length=15)
    skype = models.CharField(max_length=100)
    freelance = models.CharField(max_length=15, choices=FREELANCE_STATUS, default="Available")

    def __str__(self):
        return self.name
    


class Brand(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='brands/')

    def __str__(self):
        return self.name



class Feedback(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    feedback = models.TextField(max_length=255)

    def __str__(self):
        return self.client.name
    


class BlogCategory(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)

    def __str__(self):
        return self.title
    


class Tag(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)

    def __str__(self):
        return self.title
    

class Blog(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='project/', help_text="Image size must be 800*600 px")
    cover = models.ImageField(upload_to='project/', help_text="Image size must be 1500*840 px")
    blog = RichTextField()
    tags = models.ManyToManyField(Tag)
    meta_description = models.CharField(max_length=255, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)


    def __str__(self):
        return self.title
    

class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    comment = models.TextField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)


    def __str__(self):
        return self.blog.title
    
    class Meta:
        ordering = ('created_at', )
    

class Reply(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, null=True, blank=True)
    reply = models.TextField(max_length=500, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)




#pricing
class Pricing(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    price = models.CharField(max_length=100)
    icon = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class Pricing_Options(models.Model):
    pricing = models.ForeignKey(Pricing, on_delete=models.CASCADE)
    option = models.CharField(max_length=255)




STATUS_CHOICES = (
    ('pending','Pending'),
    ('received', 'Received'),
    ('running','Running'),
    ('completed','Completed'),
    ('canceled','Canceled'),
)

class Order(models.Model):
    pricing = models.ForeignKey(Pricing, on_delete=models.CASCADE)
    subject = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    phone = models.CharField(max_length=15)
    details = models.TextField()
    budget = models.CharField(max_length=100)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="pending")

app/views/blog.py
from django.shortcuts import render, redirect
from django.contrib import messages

from ..models import Blog, BlogCategory
from ..forms import NewCommentForm

def index(request):
    categories = BlogCategory.objects.all()
    blogs = Blog.objects.all()

    context = {
        'categories': categories,
        'blogs': blogs,
    }
    return render(request, 'blog/index.html', context)



def show(request, slug):
    blog = Blog.objects.get(slug = slug)
    form = NewCommentForm()

    if request.method == 'POST':
        form = NewCommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.blog = blog
            comment.save()

            return redirect('blog.show', blog.slug)
        else:
            messages.error(request, 'An error occured during commenting')

    context = {
        'blog': blog,
        'form' : form
    }

    return render(request, 'blog/show.html', context)



def category(request, slug):
    categories = BlogCategory.objects.all()
    category = BlogCategory.objects.get(slug= slug)
    blogs = Blog.objects.filter(category = category.id)

    context = {
        'category': category,
        'categories': categories,
        'blogs': blogs
    }

    return render(request, 'blog/index.html', context)

app/templates/blog/category.html
<!-- Start category  ============================================= -->
<div class="blog-style-one-area blog-area default-padding-top">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 offset-lg-2">
                <div class="site-heading text-center">
                    <h4 class="sub-title">Learn</h4>
                    {% if category %}
                    <h2 class="title">{{ category.title }}</h2>
                    {% else %}
                    <h2 class="title">My blogs</h2>
                    {% endif %}
                    <div class="devider"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="d-flex">

            {% for category in categories %}
            <!-- Single item -->
            <div class="card bg-white border-0">
                <h4 class="m-0 p-2">
                    <a href="{% url 'blog.category' category.slug %}" class="ps-3 pe-3">{{ category.title }}</a>
            </div>
            <!-- End Single item -->
            {% endfor %}


        </div>
    </div>

</div>
<!-- End category -->

app/templates/blog/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% include 'blog/category.html' %}

<!-- Start Blog 
    ============================================= -->
<div class="blog-style-one-area blog-area default-padding">

    <div class="container">
        <div class="row">

            {% for blog in blogs %}
            <!-- Single item -->
            <div class="blog-style-one mb-30 col-lg-4 col-md-6">
                <div class="item">
                    <div class="thumb">
                        <a href="{% url 'blog.show'  blog.slug %}"><img src="{{ HTTP_HOST }}/media/{{ blog.image }}"
                                alt="Thumb"></a>
                    </div>
                    <div class="info">
                        <h4>
                            <a href="{% url 'blog.show'  blog.slug %}">{{ blog.title }}</a>
                        </h4>
                        <div class="meta">
                            <ul>
                                <li>
                                    <i class="fas fa-calendar-alt"></i> {{ blog.created_at }}
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Single item -->
            {% endfor %}


        </div>
    </div>

</div>
<!-- End Blog -->

{% endblock %}

app/templates/blog/show.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div id="blog" class="blog-style-one-area blog-area default-padding">
    <div class="shape-animated-right">
        <img src="{% static 'assets/img/shape/1.webp' %}" alt="Shape">
    </div>

    <div class="container">
        <a href="{% url 'blog.index' %}"><i class="fas fa-arrow-left"></i> Go Back</a>

        <div class="blog-single-content">
            <div class="thumb">
                <a href="#"><img src="{{ HTTP_HOST }}/media/{{ blog.cover }}" alt="Thumb"></a>
            </div>
            <div class="info">
                <div class="meta">
                    <ul>
                        <li>
                            <a href="#"><i class="fas fa-user-circle"></i> Admin</a>
                        </li>
                        <li>
                            <a href="#"><i class="fas fa-comments"></i> 26 Comments</a>
                        </li>
                    </ul>
                </div>
                {{ blog.blog | safe }}
            </div>
        </div>

        <!-- Post Author -->
        <div class="post-author">
            <div class="thumb">
                <img src="{{ HTTP_HOST }}/media/{{ blog.user.userinfo.image }}" alt="Thumb">
            </div>
            <div class="content">
                <h4><a href="#">{{ blog.user.first_name }} {{ blog.user.last_name }}</a></h4>
                <a href="#">{{ blog.user.email }}</a>
                <p>{{ blog.user.userinfo.short_description }}</p>
            </div>
        </div>
        <!-- Post Author -->

        <!-- Post Tags Share -->
        <div class="post-tags share">
            <div class="tags">
                <h4>Tags: </h4>
                {% for tag in blog.tags.all %}
                <a href="#">{{ tag.title }}</a>
                {% endfor %}
            </div>

            <div class="social">
                <h4>Share:</h4>
                <ul>
                    <li>
                        <a class="facebook" href="#" target="_blank"><i class="fab fa-facebook-f"></i></a>
                    </li>
                    <li>
                        <a class="twitter" href="#" target="_blank"><i class="fab fa-twitter"></i></a>
                    </li>
                    <li>
                        <a class="pinterest" href="#" target="_blank"><i class="fab fa-pinterest-p"></i></a>
                    </li>
                    <li>
                        <a class="linkedin" href="#" target="_blank"><i class="fab fa-linkedin-in"></i></a>
                    </li>
                </ul><!-- End Social Share -->
            </div>
        </div>
        <!-- Post Tags Share -->

        <!-- Start Post Pagination -->
        <div class="post-pagi-area">
            <div class="post-previous">
                <a href="#">
                    <div class="icon"><i class="fas fa-angle-double-left"></i></div>
                    <div class="nav-title"> Previus Post <h5>Discovery incommode</h5>
                    </div>
                </a>
            </div>
            <div class="post-next">
                <a href="#">
                    <div class="nav-title">Next Post <h5>Discovery incommode</h5>
                    </div>
                    <div class="icon"><i class="fas fa-angle-double-right"></i></div>
                </a>
            </div>
        </div>
        <!-- End Post Pagination -->

        <!-- Start Blog Comment -->
        <div class="blog-comments">
            <div class="comments-area">
                <div class="comments-title">
                    <h3>{{ blog.comment_set.count }} Comments On “{{ blog.title }}”</h3>
                    <div class="comments-list">
                        {% for comment in blog.comment_set.all %}
                        <div class="comment-item">
                            <div class="avatar">
                                <img src="{% static 'assets/img/user-avatar.png' %}" alt="Author">
                            </div>
                            <div class="content">
                                <div class="title">
                                    <h5>{{ comment.name }} </h5>
                                    <span>{{ comment.created_at |date:'Y-m-d H:i' }}</span>
                                </div>
                                <p>
                                    {{ comment.comment }}
                                </p>
                            </div>
                        </div>
                        {% for reply in comment.reply_set.all %}
                        <div class="comment-item reply">
                            <div class="avatar">
                                <img src="{{ HTTP_HOST }}/media/{{ reply.user.userinfo.image }}" alt="Author">
                            </div>
                            <div class="content">
                                <div class="title">
                                    <h5>{{ reply.user.first_name }} {{ reply.user.last_name }}</h5>
                                    <span>{{ comment.created_at }}</span>
                                </div>
                                <p>
                                    Delivered ye sportsmen zealously arranging frankness estimable as. Nay
                                    any article enabled musical shyness yet sixteen yet blushes. Entire its
                                    the did figure wonder off. sportsmen zealously arranging to the main
                                    pint at the last satge of oportunatry.
                                </p>
                            </div>
                        </div>
                        {% endfor %}
                        {% endfor %}
                    </div>
                </div>
                <div class="comments-form">
                    <div class="title">
                        <h3>Leave a comments</h3>
                    </div>
                    <form action="#" class="contact-comments" method="POST">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ form.name }}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <!-- Email -->
                                    {{ form.email }}
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group comments">
                                    <!-- Comment -->
                                    {{ form.comment }}
                                </div>
                                <div class="form-group full-width submit">
                                    <button class="btn btn-animation dark border" type="submit">Post
                                        Comment</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- End Comments Form -->

    </div>
</div>
{% endblock %}