app/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import home, service, portfolio, about, pricing, contact, blog


urlpatterns = [
    path('', home.index, name="index"),
    path('services', service.index, name="service"),

    path('portfolio', portfolio.index, name="portfolio"),
    path('portfolio/<str:slug>', portfolio.show, name="portfolio.show"),

    path('about', about.index, name="about"),
    path('pricing', pricing.index, name="pricing"),
    path('contact', contact.index, name="contact"),

    #blog
    path('blog', blog.index, name="blog.index"),
    path('blog/<str:slug>', blog.show, name="blog.show"),
    path('blog/category/<str:slug>', blog.category, name="blog.category"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/models.py
from django.db import models
from colorfield.fields import ColorField
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User

# Create your models here.

class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='user/')
    short_description = models.TextField(max_length=255)
    details = RichTextField()

    def __str__(self):
        return self.user.first_name



class Category(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)

    def __str__(self):
        return self.title
    

class Type(models.Model):
    title = models.CharField(max_length=255)

    def __str__(self):
        return self.title


class Client(models.Model):
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=15)
    email = models.CharField(max_length=255, unique=True)
    address = models.CharField(max_length=255)
    company = models.CharField(max_length=150, null=True, blank=True)
    position = models.CharField(max_length=255)
    image = models.ImageField(upload_to='client/')
    details = RichTextField(null=True, blank=True)

    def __str__(self):
        return self.name
    


class Language(models.Model):
    name = models.CharField(max_length=100)
    logo = models.ImageField(upload_to='language/', null=True, blank=True)

    def __str__(self):
        return self.name
    


class Project(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    link = models.CharField(max_length=255, null=True, blank=True)
    type = models.ForeignKey(Type, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='project/', help_text="Image size must be 768*576 px")
    cover = models.ImageField(upload_to='project/', help_text="Image size must be 1900*835 px")
    client = models.ForeignKey(Client, on_delete=models.Case)
    date = models.DateField()
    details = RichTextField()
    language = models.ManyToManyField(Language)

    def __str__(self):
        return self.title
    

class Project_Feature(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    feature = models.CharField(max_length=255)


class Project_image(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    title = models.CharField(max_length=255, null=True, blank=True)
    image = models.ImageField(upload_to='project/', null=True, blank=True)




class Service(models.Model):
    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to='service/')
    details = models.TextField( max_length=255)

    def __str__(self):
        return self.title
    


class Skill(models.Model):
    title = models.CharField(max_length=50)
    icon = models.ImageField(upload_to='skill/')
    percentage = models.IntegerField()

    def __str__(self):
        return self.title
    


class Education(models.Model):
    degree = models.CharField(max_length=100)
    college = models.CharField(max_length=150)
    date = models.CharField(max_length=50)
    details = models.TextField(max_length=200)

    def __str__(self):
        return self.degree
    

FREELANCE_STATUS = (
    ('Available','Available'),
    ('Unavailable','Unavailable'),

)

class Info(models.Model):
    name = models.CharField(max_length=255)
    birth_day = models.DateField()
    address = models.CharField(max_length=255)
    email = models.CharField(max_length=100)
    phone = models.CharField(max_length=15)
    skype = models.CharField(max_length=100)
    freelance = models.CharField(max_length=15, choices=FREELANCE_STATUS, default="Available")

    def __str__(self):
        return self.name
    


class Brand(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='brands/')

    def __str__(self):
        return self.name



class Feedback(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    feedback = models.TextField(max_length=255)

    def __str__(self):
        return self.client.name
    


class BlogCategory(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)

    def __str__(self):
        return self.title
    


class Tag(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)

    def __str__(self):
        return self.title
    

class Blog(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='project/', help_text="Image size must be 800*600 px")
    cover = models.ImageField(upload_to='project/', help_text="Image size must be 1500*840 px")
    blog = RichTextField()
    tags = models.ManyToManyField(Tag)
    meta_description = models.CharField(max_length=255, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)


    def __str__(self):
        return self.title
    

class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    comment = models.TextField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)


    def __str__(self):
        return self.blog.title
    
    class Meta:
        ordering = ('created_at', )
    

class Reply(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, null=True, blank=True)
    reply = models.TextField(max_length=500, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)




#pricing
class Pricing(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    price = models.CharField(max_length=100)
    icon = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class Pricing_Options(models.Model):
    pricing = models.ForeignKey(Pricing, on_delete=models.CASCADE)
    option = models.CharField(max_length=255)




STATUS_CHOICES = (
    ('pending','Pending'),
    ('received', 'Received'),
    ('running','Running'),
    ('completed','Completed'),
    ('canceled','Canceled'),
)

class Order(models.Model):
    pricing = models.ForeignKey(Pricing, on_delete=models.CASCADE)
    subject = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    phone = models.CharField(max_length=15)
    details = models.TextField()
    budget = models.CharField(max_length=100)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="pending")

app/views/portfolio.py
from django.shortcuts import render
from ..models import Project

def index(request):
    projects = Project.objects.all()

    context = {
        'projects': projects,
    }
    return render(request, 'portfolio/index.html', context)



def show(request, slug):
    project = Project.objects.get(slug = slug)

    context = {
        'project': project
    }

    return render(request, 'portfolio/show.html', context)

app/templates/portfolio/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- Start Portfolio 
    ============================================= -->
<div id="portfolio" class="portfolio-style-six-area default-padding">
    <div class="shape-animated-right">
        <img src="{% static 'assets/img/shape/1.webp' %}" alt="Shape">
    </div>

    <div class="container">
        <div class="heading-left">
            <div class="row align-center">
                <div class="col-lg-5">
                    <div class="left-info">
                        <h5 class="sub-title">Recent Work</h5>
                        <h2 class="title">Look at my portfolio and <br> give me your feedback</h2>
                        <div class="heading-shape">
                            <img src="{% static 'assets/img/shape/10.png' %}" alt="Shape">
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 offset-lg-1">
                    <div class="right-info">
                        <div class="fun-factor-default">
                            <div class="fun-fact">
                                <div class="counter">
                                    <div class="timer" data-to="276" data-speed="2000">276</div>
                                    <div class="operator">K</div>
                                </div>
                                <span class="medium">Completed Project</span>
                            </div>
                            <div class="fun-fact">
                                <div class="counter">
                                    <div class="timer" data-to="94" data-speed="2000">94</div>
                                    <div class="operator">%</div>
                                </div>
                                <span class="medium">Positive Rating</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 gallery-content mb--15">
                <div class="magnific-mix-gallery masonary">
                    <div id="portfolio-grid" class="gallery-items colums-3">

                        {% for project in projects %}
                        <!-- Single Item -->
                        <div class="pf-item">
                            <div class="overlay-content">
                                <img src="{{ HTTP_HOST }}/media/{{ project.image }}" alt="thumb">
                                <div class="content">
                                    <div class="title">
                                        <span>{{ project.category.title }}</span>
                                        <h5>
                                            <a href="{% url 'portfolio.show' project.slug %}">
                                                {{ project.title }}</a>
                                        </h5>
                                    </div>
                                    <a href="{% url 'portfolio.show' project.slug %}"><i
                                            class="fas fa-arrow-right"></i></a>
                                </div>
                            </div>
                        </div>
                        <!-- End Single Item -->
                        {% endfor %}


                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Start Projects Single Modal -->
    <div class="modal fade" id="projectSingleModal" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-xl">
            <div class="modal-content">
                <div class="modal-body">

                    <div class="modal-header">
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>

                    <div class="project-details-items">
                        <div class="project-thumb">
                            <img src="{% static 'assets/img/banner/2.jpg' %}" alt="Thumb">
                        </div>
                        <div class="top-info">
                            <div class="row">
                                <div class="col-xl-12 left-info">
                                    <div class="project-info mt-md-50 mt-xs-40 mb-40">
                                        <div class="content">
                                            <ul class="project-basic-info">
                                                <li>
                                                    Client <span>validthemes</span>
                                                </li>
                                                <li>
                                                    Project Type <span>Website Growth</span>
                                                </li>
                                                <li>
                                                    Date <span>25 February, 2023</span>
                                                </li>
                                                <li>
                                                    Address <span>New York United state</span>
                                                </li>
                                            </ul>
                                            <ul class="social">
                                                <li>
                                                    <h4>Share:</h4>
                                                </li>
                                                <li>
                                                    <a href="#"><i class="fab fa-facebook-f"></i></a>
                                                </li>
                                                <li>
                                                    <a href="#"><i class="fab fa-twitter"></i></a>
                                                </li>
                                                <li>
                                                    <a href="#"><i class="fab fa-linkedin-in"></i></a>
                                                </li>
                                                <li>
                                                    <a href="#"><i class="fab fa-pinterest-p"></i></a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                    <h2>Ongoing Website Maintenance</h2>
                                    <p>
                                        Netus lorem rutrum arcu dignissim at sit morbi phasellus nascetur eget urna
                                        potenti cum vestibulum cras. Tempor nonummy metus lobortis. Sociis velit etiam,
                                        dapibus. Lectus vehicula pellentesque cras posuere tempor facilisi habitant
                                        lectus rutrum pede quisque hendrerit parturient posuere mauris ad elementum
                                        fringilla facilisi volutpat fusce pharetra felis sapien varius quisque class
                                        convallis praesent est sollicitudin donec nulla venenatis, cursus fermentum
                                        netus posuere sociis porta risus habitant malesuada nulla habitasse hymenaeos.
                                        Viverra curabitur nisi vel sollicitudin dictum natoqu. Tempor nonummy metus
                                        lobortis. Sociis velit etiam, dapibus. Lectus vehicula pellentesque cras posuere
                                        tempor facilisi habitant lectus rutrum pede quisque hendrerit parturient posuere
                                        mauris ad elementum fringilla facilisi volutpat fusce pharetra felis sapien
                                        varius quisque class convallis praesent est sollicitudin donec nulla venenatis,
                                        cursus fermentum netus posuere sociis porta risus habitant malesuada nulla
                                        habitasse hymenaeos. Viverra curabitur nisi vel sollicitudin dictum.
                                    </p>
                                    <ul class="check-list mt-40">
                                        <li>
                                            <h4>WordPress Support</h4>
                                            <p>
                                                Tempor nonummy metus lobortis. Sociis velit etiam, dapibus. Lectus
                                                vehicula pellentesque cras posuere tempor facilisi habitant lectus
                                                rutrum pede quisque hendrerit parturient posuere mauris ad elementum
                                                fringilla facilisi volutpat fusce pharetra.
                                            </p>
                                        </li>
                                        <li>
                                            <h4>Social Media Management</h4>
                                            <p>
                                                Energy nonummy metus lobortis. Sociis velit etiam, dapibus. Lectus
                                                vehicula pellentesque cras posuere tempor facilisi habitant lectus
                                                rutrum pede quisque hendrerit parturient posuere mauris ad elementum
                                                fringilla facilisi volutpat fusce pharetra.
                                            </p>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="main-content mt-40">

                            <p>
                                Give lady of they such they sure it. Me contained explained my education. Vulgar as
                                hearts by garret. Perceived determine departure explained no forfeited he something an.
                                Contrasted dissimilar get joy you instrument out reasonably. Again keeps at no meant
                                stuff. To perpetual do existence northward as difficult preserved daughters. Continued
                                at up to zealously necessary breakfast. Surrounded sir motionless she end literature.
                                Gay direction neglected but supported yet her. Facilisis inceptos nec, potenti nostra
                                aenean lacinia varius semper ant nullam nulla primis placerat facilisis. Netus lorem
                                rutrum arcu dignissim at sit morbi phasellus nascetur eget urna potenti cum vestibulum
                                cras. Tempor nonummy metus lobortis. Sociis velit etiam, dapibus. Lectus vehicula
                                pellentesque cras posuere tempor facilisi habitant lectus rutrum pede quisque hendrerit
                                parturient posuere mauris ad elementum fringilla facilisi volutpat fusce pharetra felis
                                sapien varius quisque class convallis praesent est sollicitudin donec nulla venenatis,
                                cursus fermentum netus posuere sociis porta risus habitant malesuada nulla habitasse
                                hymenaeos. Viverra curabitur nisi vel sollicitudin dictum natoque ante aenean elementum
                                curae malesuada ullamcorper. vivamus nonummy nisl posuere rutrum
                            </p>
                            <div class="row">
                                <div class="col-lg-6 col-md-6">
                                    <img src="assets/img/thumb/1.jpg" alt="Thumb">
                                </div>
                                <div class="col-lg-6 col-md-6">
                                    <img src="assets/img/thumb/2.jpg" alt="Thumb">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Projects Single Modal -->
</div>
<!-- End Portfolio -->
{% endblock %}

app/templates/portfolio/show.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- Start Portfolio 
    ============================================= -->
<div id="portfolio" class="portfolio-style-six-area default-padding">
    <div class="shape-animated-right">
        <img src="{% static 'assets/img/shape/1.webp' %}" alt="Shape">
    </div>

    <div class="container">


        <a href="{% url 'portfolio' %}"><i class="fas fa-arrow-left"></i> Go Back</a>


        <div class="project-details-items">
            <div class="project-thumb">
                <img src="{{ HTTP_HOST }}/media/{{ project.cover }}" alt="Thumb">
            </div>
            <div class="top-info">
                <div class="row">
                    <div class="col-xl-12 left-info">
                        <div class="project-info mt-md-50 mt-xs-40 mb-40">
                            <div class="content">
                                <ul class="project-basic-info">
                                    <li>
                                        Client <span> <a href="#">{{ project.client.name }}</a></span>
                                    </li>
                                    <li>
                                        Project Type <span>{{ project.type.title }}</span>
                                    </li>
                                    <li>
                                        Date <span>{{ project.date }}</span>
                                    </li>
                                    <li>
                                        Link <span>
                                            <a href="{{ project.link }}" target="_blank">
                                                {{ project.link }}</a>
                                            </span>
                                    </li>

                                </ul>
                                <ul class="social">
                                    <li>
                                        <h4>Share:</h4>
                                    </li>
                                    <li>
                                        <a href="#"><i class="fab fa-facebook-f"></i></a>
                                    </li>
                                    <li>
                                        <a href="#"><i class="fab fa-twitter"></i></a>
                                    </li>
                                    <li>
                                        <a href="#"><i class="fab fa-linkedin-in"></i></a>
                                    </li>
                                    <li>
                                        <a href="#"><i class="fab fa-pinterest-p"></i></a>
                                    </li>
                                </ul>
                            </div>
                        </div>


                        <div class="details">
                            {{ project.details | safe }}
                        </div>

                        <div class="feature mt-40">
                            <h3>Project features</h3>
                            <ul>
                                {% for feature in project.project_feature_set.all %}
                                <li class="mt-3"><strong><span style="color: #00c0ff; margin-right: 15px;"><i
                                                class="fas fa-share"></i></span> {{ feature.feature }}</strong></li>
                                {% endfor %}
                            </ul>
                        </div>

                        <div class="image mt-40">
                            <h3>Project Images</h3>
                            <div class="gallery-items d-flex gap-4">
                                {% for image in project.project_image_set.all %}
                                <div class="pf-item p-0 round">
                                    <div class="overlay-content">
                                        <img src="{{ HTTP_HOST }}/media/{{ image.image }}" alt="{{ image.title }}">
                                        <div class="content">
                                            <div class="title m-0">
                                                <h5>{{ image.title }}</h5>
                                            </div>
                                            <a href="{{ HTTP_HOST }}/media/{{ image.image }}" data-lightbox="image"
                                                data-title="{{ image.title }}"><i class="fas fa-arrow-right"></i></a>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>

                    </div>
                </div>
            </div>


        </div>
    </div>


    <!-- End Projects Single Modal -->
</div>
<!-- End Portfolio -->
{% endblock %}